###
GET http://localhost:5180/api/v1/categories HTTP/1.1
content-type: application/json

###
POST http://localhost:5180/api/v1/categories HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
  "name": "Air-purifying plants",
  "imageUrl": "https://picsum.photos/200"
}

###
PATCH http://localhost:5180/api/v1/categories/22f2e07f-6b00-4239-989c-64a0339dfd95 HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
  "name": "Non-toxic plants"
}

###
DELETE http://localhost:5180/api/v1/categories/4735d66d-032f-4bc1-ac1b-2cbd6a93a184 HTTP/1.1
content-type: application/json
Authorization: Bearer 