###
GET http://localhost:5180/api/v1/images/product/e88c76fd-2eb7-4e80-b9b9-17e778ddd8f0 HTTP/1.1
content-type: application/json
Authorization: Bearer 
###
POST  http://localhost:5180/api/v1/images/product/e88c76fd-2eb7-4e80-b9b9-17e778ddd8f0 HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
  "imageUrl": "https://picsum.photos/700"
}

###
PATCH  http://localhost:5180/api/v1/images/product/e88c76fd-2eb7-4e80-b9b9-17e778ddd8f0 HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
  "imageId": "67397370-3727-4e5f-a527-b6a39ca59feb"
}

###
DELETE  http://localhost:5180/api/v1/images/product/e88c76fd-2eb7-4e80-b9b9-17e778ddd8f0 HTTP/1.1
content-type: application/json
Authorization: 

{
  "imageId": "9fa51757-0cd5-4ffa-9ed7-589c0094f127"
}

###
PATCH  http://localhost:5180/api/v1/images/1f6452a4-9d24-4d2b-a2dc-581203e04fbb HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
  "description": "plant"
}

###
DELETE  http://localhost:5180/api/v1/images/ca7951b3-8488-45fd-bf18-85f5aa467f0f HTTP/1.1
content-type: application/json
Authorization: Bearer 