###
GET http://localhost:5180/api/v1/orders HTTP/1.1
content-type: application/json
Authorization: Bearer 

###
POST http://localhost:5180/api/v1/orders HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyY2JmMTc1Zi0yMmZmLTRhMTctOTA0Zi1jNTBlZTRkYjU1ODgiLCJyb2xlIjoiQ3VzdG9tZXIiLCJuYmYiOjE3MDM3NTEyNTYsImV4cCI6MTcwMzkyNDA1NiwiaWF0IjoxNzAzNzUxMjU2LCJpc3MiOiJFdmVyZ3JlZW5BZG1pbiIsImF1ZCI6IkV2ZXJncmVlbiJ9.t-wCUd3bXMFU0sg9rrOsw_AfXgJmUkEWFwlp9uKt6t0

{
  "orderDetails": [
    {
      "productId": "0bfb3b77-d015-4a52-b7d2-d2a15eae2f0e",
      "quantity": 2
    },
    {
      "productId": "0bfc5e2c-d6f3-4e3b-826d-95db5466f873",
      "quantity": 1
    },
        {
      "productId": "2c3d7c12-7f50-44c3-9250-b66fc233d26e",
      "quantity": 1
    }
  ]
}

###
PATCH http://localhost:5180/api/v1/orders/3b2ba914-2428-4da7-aa15-85ef92c143e8 HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
  "orderStatus": "Shipped"
}

###
DELETE http://localhost:5180/api/v1/orders/63acdf80-c6d5-4d88-ab67-4ea07e30a4e4 HTTP/1.1
content-type: application/json
Authorization: Bearer 