###
GET http://localhost:5180/api/v1/products HTTP/1.1
content-type: application/json

###
GET http://localhost:5180/api/v1/products/e88c76fd-2eb7-4e80-b9b9-17e778ddd8f0 HTTP/1.1
content-type: application/json

###
POST http://localhost:5180/api/v1/products HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
  "title": "Tillandsia mix",
  "latinName": "Tillandsia",
  "price": 12.50,
  "description": "Nice plant mix",
  "categoryId": "22619216-3ffe-4c2e-ac33-47f7a9e94163",
  "productImages": [
    {
      "imageUrl": "https://picsum.photos/200",
      "description": "test"
    },
    {
      "imageUrl": "https://picsum.photos/200",
      "description": "test2"
    }
  ],
  "productDetails": {
    "size": "Small",
    "watering": "Low",
    "light": "Medium",
    "difficulty": "Medium",
    "hanging": true,
    "nonToxic": true,
    "airPurifying": false
  },
  "inventory": 13

}

###
PATCH http://localhost:5180/api/v1/products/e88c76fd-2eb7-4e80-b9b9-17e778ddd8f0 HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
  "price": "14.59"
}

###
PATCH http://localhost:5180/api/v1/products/e88c76fd-2eb7-4e80-b9b9-17e778ddd8f0 HTTP/1.1
content-type: application/json
Authorization: 

{
  "latinName": "Tillandsia officinalis",
  "description": "Elegant air plant"
}

###
PATCH http://localhost:5180/api/v1/products/inventory/e88c76fd-2eb7-4e80-b9b9-17e778ddd8f0 HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
  "inventoryChange": 8
}

###
PATCH http://localhost:5180/api/v1/products/details/e88c76fd-2eb7-4e80-b9b9-17e778ddd8f0 HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
  "watering": "Low"
}

###
DELETE http://localhost:5180/api/v1/products/63acdf80-c6d5-4d88-ab67-4ea07e30a4e4 HTTP/1.1
content-type: application/json
Authorization: Bearer 