###
POST http://localhost:5180/api/v1/auth/profile HTTP/1.1
content-type: application/json

{
  "name": "Andrew Miller",
  "email": "andrewm@mail.com",
  "password": ,
  "avatar": "https://picsum.photos/200"
}

###
GET http://localhost:5180/api/v1/users HTTP/1.1
content-type: application/json
Authorization: Bearer 

###
Authorization: Bearer 

###
PATCH http://localhost:5180/api/v1/auth/profile/password/0c615dda-a150-4f4b-8e66-1371a9e0b318 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwYzYxNWRkYS1hMTUwLTRmNGItOGU2Ni0xMzcxYTllMGIzMTgiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMyNDU2OTAsImV4cCI6MTcwMzQxODQ5MCwiaWF0IjoxNzAzMjQ1NjkwLCJpc3MiOiJFdmVyZ3JlZW5BZG1pbiIsImF1ZCI6IkV2ZXJncmVlbiJ9.nYjSzWPA1gTYffp0J0zWu7YcnPXnwRMLV04j2e7C2MU

{
  "password":
}

###
PATCH http://localhost:5180/api/v1/auth/profile/ed6a2c95-e2af-434d-874d-b6eefd54930c HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
  "email": "andrew.miller@mail.com"
}


###
DELETE http://localhost:5180/api/v1/auth/profile/a72edcea-3572-4432-936e-a1e92f7e8172 HTTP/1.1
content-type: application/json
Authorization: Bearer 

###
PATCH http://localhost:5180/api/v1/users/ed6a2c95-e2af-434d-874d-b6eefd54930c HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
  "role": "Customer"
}

###
DELETE http://localhost:5180/api/v1/users/c8a57e46-26e2-4954-bd8a-423e2780c202 HTTP/1.1
content-type: application/json
Authorization: Bearer 
